{
 "title": "Attacks",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": "select src_ip from conexiones_4 where src_ip like \"%192.168.0.%\";"
   }
  ]
 },
 "panels": [
  { "title": "Incorrect Routing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Incorrect Routing",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(fecha) AS \"time\",\n  src_mac as \"Source MAC\",\n  src_ip as \"Source IP\",\n  dest_mac as \"Destination MAC\",\n  dest_ip as \"Destination IP\"\nFROM enrutamiento_incorrecto\nWHERE\n  $__timeFilter(fecha) AND (src_ip IN ($Device) OR dest_ip IN ($Device))\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Routing status %",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeFilter(UNIX_TIMESTAMP(fecha)) as \"time\",\n  count(*) as \"Incorrect routing packets\"\nFROM enrutamiento_incorrecto\nWHERE\n  $__timeFilter(fecha) AND (src_ip IN ($Device) OR dest_ip IN ($Device))\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeFilter(UNIX_TIMESTAMP(fecha)) as \"time\",\n  count(*) as \"Total packets\"\nFROM conexiones_4\nWHERE\n  $__timeFilter(fecha) AND (src_ip IN ($Device) OR dest_ip IN ($Device))\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Man in the Middle Attacks - ARP Poisoning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "ARP Poisoning",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(fecha) AS \"time\",\n  src_mac as \"Attacker MAC\",\n  src_ip as \"Suplanted IP\",\n  dest_mac as \"Victim MAC\",\n  dest_ip as \"Victim IP\"\nFROM arp_poisoning\nWHERE\n  $__timeFilter(fecha) AND (src_ip IN ($Device) OR dest_ip in ($Device))\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Last ARP Poisoning Attack (Hours)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TIMEDIFF((NOW() - INTERVAL 2 HOUR), D.time) as \"Diff\"\nFROM (\n  SELECT\n  (fecha - INTERVAL 2 HOUR) as \"time\"\n  FROM arp_poisoning\n  WHERE\n  $__timeFilter(fecha) AND (src_ip IN ($Device) OR dest_ip in ($Device))\n  ORDER BY fecha DESC\n  LIMIT 1\n  ) D"
    }
   ]
  },
  {
   "title": "Last Victim MAC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(fecha) AS \"time\",\n  dest_mac as \"Victim MAC\"\nFROM arp_poisoning\nWHERE\n  $__timeFilter(fecha) AND (src_ip IN ($Device) OR dest_ip in ($Device))\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Last  Attacker MAC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(fecha) AS \"time\",\n  src_mac as \"Attacker MAC\"\nFROM arp_poisoning\nWHERE\n  $__timeFilter(fecha) AND (src_ip IN ($Device) OR dest_ip in ($Device))\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Last Suplanted IP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(fecha) AS \"time\",\n  src_ip as \"Suplanted IP\"\nFROM arp_poisoning\nWHERE\n  $__timeFilter(fecha) AND (src_ip IN ($Device) OR dest_ip in ($Device))\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Man in the Middle Attacks - DHCP Spoofing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "DHCP Spoofing",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(fecha) AS \"time\",\n  src_mac as \"Attacker MAC\",\n  dest_mac as \"Victim MAC\",\n  dhcp_ip as \"DHCP IP (Attacker IP)\",\n  your_ip as \"Offered IP\"\nFROM dhcp_spoofing\nWHERE\n  $__timeFilter(fecha) AND (dhcp_ip IN ($Device) OR your_ip in ($Device))\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Last DHCP Spoofing Attack",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT TIMEDIFF((NOW() - INTERVAL 2 HOUR), D.time) as \"Diff\"\nFROM (\n  SELECT\n  (fecha - INTERVAL 2 HOUR) as \"time\"\n  FROM dhcp_spoofing\n  WHERE\n  $__timeFilter(fecha) AND (dhcp_ip IN ($Device) OR your_ip in ($Device))\n  ORDER BY fecha DESC\n  LIMIT 1\n  ) D"
    }
   ]
  },
  {
   "title": "Last Victim MAC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(fecha) AS \"time\",\n  dest_mac\nFROM dhcp_spoofing\nWHERE\n  $__timeFilter(fecha) AND (dhcp_ip IN ($Device) OR your_ip in ($Device))"
    }
   ]
  },
  {
   "title": "Last Attacker MAC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(fecha) AS \"time\",\n  src_mac\nFROM dhcp_spoofing\nWHERE\n  $__timeFilter(fecha) AND (dhcp_ip IN ($Device) OR your_ip in ($Device))"
    }
   ]
  },
  {
   "title": "Last DHCP IP (Attacker IP)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(fecha) AS \"time\",\n  dhcp_ip\nFROM dhcp_spoofing\nWHERE\n  $__timeFilter(fecha) AND (dhcp_ip IN ($Device) OR your_ip in ($Device))"
    }
   ]
  },
  { "title": "Possible DoS Attacks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Possible DoS",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(fecha) AS \"time\",\n  src_ip as \"Attacker IP\",\n  dest_ip as \"Victim IP\",\n  paquetes as \"Packets\",\n  CONCAT(pais, ' (', pais_codigo,')') as \"Country\",\n  CONCAT(region, ' (', region_codigo,')') as \"Region\",\n  ciudad as \"City\",\n  latitud as \"Latitude\",\n  longitud as \"Longitude\"\nFROM posible_dos\nWHERE\n  $__timeFilter(fecha) AND (src_ip IN ($Device) OR dest_ip in ($Device))\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Heat Map",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(fecha) AS \"time\",\n  CAST(latitud AS DECIMAL(15,8)) as \"Latitude\",\n  CAST(longitud AS DECIMAL(15,8))as \"Longitude\",\n  CAST(paquetes AS SIGNED) as \"Packets\"\nFROM posible_dos\nWHERE\n  $__timeFilter(fecha) AND (src_ip IN ($Device) OR dest_ip in ($Device))\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Total Packets",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(fecha) AS \"time\",\n  src_ip,\n  SUM(CAST(paquetes as SIGNED)) as \"\"\nFROM posible_dos\nWHERE\n  $__timeFilter(fecha) AND (src_ip IN ($Device) OR dest_ip in ($Device))\nGROUP BY fecha, src_ip\nORDER BY fecha"
    }
   ]
  }
 ]
}