{
 "title": "Traffic Monitor",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": "select src_ip from conexiones_4 where src_ip like \"%192.168.0.%\" UNION select dest_ip from conexiones_4 where dest_ip like \"%192.168.0.%\";"
   }
  ]
 },
 "panels": [
  {
   "title": "All Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(fecha) AS \"time\",\n  sum(CAST(datos AS SIGNED)) as \"Input traffic\"\nFROM conexiones_4\nWHERE\n  $__timeFilter(fecha) and dest_ip IN ($Device)\nGROUP BY fecha\nORDER BY fecha"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(fecha) AS \"time\",\n  sum(CAST(datos AS SIGNED)) as \"Output traffic\"\nFROM conexiones_4\nWHERE\n  $__timeFilter(fecha) and src_ip IN ($Device)\nGROUP BY fecha\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Traffic (Bytes)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeFilter(UNIX_TIMESTAMP(fecha)) as \"time\",\n  sum(IF(dest_ip IN ($Device), CAST(datos AS SIGNED), 0)) AS \"Input\",\n  sum(IF(src_ip IN ($Device), CAST(datos AS SIGNED), 0)) AS \"Output\"\nFROM conexiones_4\nWHERE\n  $__timeFilter(fecha)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Traffic (Bytes)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeFilter(UNIX_TIMESTAMP(fecha)) as \"time\",\n  sum(IF(dest_ip IN ($Device), CAST(datos AS SIGNED), 0)) AS \"Input\",\n  sum(IF(src_ip IN ($Device), CAST(datos AS SIGNED), 0)) AS \"Output\"\nFROM conexiones_4\nWHERE\n  $__timeFilter(fecha)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Input traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(fecha) AS \"time\",\n  src_ip,\n  SUM(CAST(datos AS UNSIGNED)) as \"\"\nFROM conexiones_4\nWHERE\n  $__timeFilter(fecha) AND dest_ip in ($Device)\nGROUP BY fecha, src_ip\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "Output traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(fecha) AS \"time\",\n  dest_ip,\n  sum(CAST(datos AS UNSIGNED)) as \"\"\nFROM conexiones_4\nWHERE\n  $__timeFilter(fecha) AND src_ip in ($Device)\nGROUP BY fecha, dest_ip\nORDER BY fecha"
    }
   ]
  },
  {
   "title": "All traffic",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(fecha) AS \"time\",\n  src_mac as \"Source MAC\",\n  dest_mac as \"Destination MAC\",\n  src_ip as \"Source IP\",\n  dest_ip as \"Destination IP\",\n  datos as \"Data (Bytes)\",\n  tipo as \"Type\"\nFROM conexiones_4\nWHERE\n  $__timeFilter(fecha) AND\n  src_ip in ($Device) or dest_ip in ($Device)\nORDER BY fecha"
    }
   ]
  }
 ]
}